name: Build Ubuntu
on: [push]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: apt install -y doxygen graphviz
    - name: Configure
      run: ./Configure config/travis-std
    - name: Build
      run: make && make docs
