name: ci

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        os: ['ubuntu-22.04']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Environment
      run: |
        bash -c set

    - name: Install Ubuntu build deps
      run: |
        sudo apt-get -qq update
        sudo apt-get install -yqq doxygen graphviz

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: configure and build
      run: |
        tox -e dist

    - name: make docs
      run: |
        tox -e docs
